# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'USER_INFO.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 546)
        Form.setStyleSheet("background-color: rgb(175, 255, 250);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(60, 60, 401, 371))
        self.frame.setStyleSheet("border: 1px solid black;\n"
"background-color: rgb(170, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 300, 381, 51))
        self.groupBox_2.setStyleSheet("border-color: rgb(170, 170, 255);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_exit = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_exit.setGeometry(QtCore.QRect(280, 20, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("border: 1px solid black;\n""color: rgb(255, 255, 255);\n""background-color: rgb(85, 0, 127);")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_save = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_save.setGeometry(QtCore.QRect(100, 20, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("border: 1px solid black;\n""color: rgb(255, 255, 255);\n""background-color: rgb(85, 0, 127);")
        self.btn_save.setObjectName("btn_save")


        self.btn_Add = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Add.setGeometry(QtCore.QRect(10, 20, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add.setFont(font)
        self.btn_Add.setStyleSheet("border: 1px solid black;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);")
        self.btn_Add.setObjectName("btn_Add")
        self.btn_Add.clicked.connect(self.enable_textfield)

        self.btn_delete = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_delete.setGeometry(QtCore.QRect(190, 20, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("border: 1px solid black;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 127);")
        self.btn_delete.setObjectName("btn_delete")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(9, 139, 381, 131))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.User_text = QtWidgets.QLineEdit(self.groupBox)

        self.User_text.setEnabled(False)

        self.User_text.setGeometry(QtCore.QRect(110, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.User_text.setFont(font)
        self.User_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.User_text.setObjectName("User_text")
        self.Pass_lbl = QtWidgets.QLabel(self.groupBox)
        self.Pass_lbl.setGeometry(QtCore.QRect(14, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Pass_lbl.setFont(font)
        self.Pass_lbl.setObjectName("Pass_lbl")
        self.Usr_lbl = QtWidgets.QLabel(self.groupBox)
        self.Usr_lbl.setGeometry(QtCore.QRect(14, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Usr_lbl.setFont(font)
        self.Usr_lbl.setObjectName("Usr_lbl")
        self.Pass_text = QtWidgets.QLineEdit(self.groupBox)

        self.Pass_text.setEnabled(False)

        self.Pass_text.setGeometry(QtCore.QRect(110, 80, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pass_text.setFont(font)
        self.Pass_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pass_text.setObjectName("Pass_text")
        self.User_combo = QtWidgets.QComboBox(self.frame)
        self.User_combo.setGeometry(QtCore.QRect(10, 80, 371, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.User_combo.setFont(font)
        self.User_combo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.User_combo.setObjectName("User_combo")
        self.User_combo.addItem("")
        self.User_combo.addItem("")
        self.Tbl_AccessDetail = QtWidgets.QTableWidget(Form)
        self.Tbl_AccessDetail.setGeometry(QtCore.QRect(460, 60, 171, 371))
        self.Tbl_AccessDetail.setStyleSheet("border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.Tbl_AccessDetail.setObjectName("Tbl_AccessDetail")
        self.Tbl_AccessDetail.setColumnCount(0)
        self.Tbl_AccessDetail.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_exit.setText(_translate("Form", "EXIT"))
        self.btn_save.setText(_translate("Form", "SAVE"))
        self.btn_Add.setText(_translate("Form", "ADD"))
        self.btn_delete.setText(_translate("Form", "DELETE"))
        self.Pass_lbl.setText(_translate("Form", "Password"))
        self.Usr_lbl.setText(_translate("Form", "Username"))
        self.User_combo.setItemText(0, _translate("Form", "Manager"))
        self.User_combo.setItemText(1, _translate("Form", "Operator"))

        self.btn_save.clicked.connect(self.on_save_save_data)


    def enable_textfield(self):
        self.User_text.setEnabled(True)
        self.Pass_text.setEnabled(True)

    def on_save_save_data(self):
        Username=self.User_text.text()
        Password=self.Pass_text.text()
        Post=self.User_combo.currentText()
        print(Username,Password,Post)
        conn = sqlite3.connect(r'C:\Users\omkar\PycharmProjects\Softveda_Internship\Userinfo.db')
        cur = conn.cursor()
        cur.execute('INSERT INTO User_info(Username,Password,Post) VALUES (?,?,?)', (Username, Password, Post))

       # result=cur.execute('select*from User_info')
       # print(result)
       # self.Tbl_AccessDetail.show(result)

        conn.commit()
        print("Records created successfully")


if __name__=="__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())